version: '3'

services:
  nginx: 
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3001:80'
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - api
    expose:
      - 3000
    environment:
      - REACT_APP_HYPERPORTFOLIO_API_URL=http://localhost:3001/api
  db:
    image: postgres:11.2-alpine
    volumes:
      - ./app/portfolios/sql/views/:/var/lib/postgresql/views/
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db

volumes:
  postgres_data:
  static_volume:
